### PR TITLE
add checkstyle (akin to rubocop)

### LINKED ISSUE #52: add lint checker (checkstyle?)
analogous to rubocop, we might want to have a java style / static analysis tool run as part of our travis builds.

http://checkstyle.sourceforge.net/  is a decent candidate;  presumably we can

- [x] add to gradle https://docs.gradle.org/current/userguide/checkstyle_plugin.html
    - [x] have task in gradle to run in separately
- [x] add to gradle check task so we can run it as part of build (and travis can too)

### PR DESCRIPTION
**Pull request by ndushay**
- hooks checkstyle to gradle, etc.
- tweaks to files to pass tests.  Can squash commits if desired.

also:
- console output for tests

Fixes #52

### CODE REVIEW

**Comment by ndushay** [comment]
this checkstyle PR is really and truly ready now.  I can suppress the style fix commits if folks want.

**Comment by ndushay** [comment]
Also:  this is a first pass at rules that don't seem ridiculous, but we may encounter rules we want to change as we create more code.

**Review by tingulfsen — APPROVED** [review]

**Comment by tingulfsen** [comment]
I'm not generally a fan of style checking, but this does seem to do some static-analysis type stuff that is useful. As long as we can keep turning off rules where it makes sense as done in this PR, I'm OK with it.

**Comment by ndushay** [comment]
I agree that style checks can cost more than the benefit they provide;   from this point forward, we can basically make turning off rules either a discussion or a PR with a discussion.  I already left out some rules I thought were stupid.  :-)

**Review by jmartin-sul — APPROVED** [review]

**Pull request merged**
